---
title             : "How do children produce negation?"
shorttitle        : "Negation Production"

author: 
  - name          : "First Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  this is the abstract
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
library(devtools)
library(childesr)
library(tidyverse)
library(tm)
```

# Methods

```{r}
english_negation <- get_utterances(language = "eng", age = c(0,24), role = "Target_Child")


count_types <- function(string){
  n <- nlevels(as.factor(unlist(strsplit(string, " "))))
  return(n)
}

count_tokens <- function(string){
  n <- unlist(strsplit(string, " "))
  return(length(n))
}

english_negation <-
  english_negation %>%
  filter(grepl('^no | no | no$|^not | not | not$|n\'t', gloss)) %>%
  filter(!grepl('not yet transcribed need to fix', gloss)) %>%
  mutate(clean_utterances = removeWords(gloss, c("xxx ?", "yyy ?", "um ?", "uh ?", "oh ?", "ah ?", "n ?"))) %>%
  mutate(can = grepl('^can | can | can$|cannot|can\'t', clean_utterances)) %>%
  mutate(do = grepl('^do | do | do$|don\'t', clean_utterances)) %>%
  mutate(n_types_clean = unlist(lapply(clean_utterances, count_types))) %>%
  mutate(n_tokens_clean = unlist(lapply(clean_utterances, count_tokens))) %>%
  mutate(type_token_ratio = n_types_clean/n_tokens_clean)




write.csv(english_negation, file="raw_data/eng_negation_undertwo.csv")
```

## Participants

## Material

## Procedure

## Data analysis

# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
